server:
  port: 8001

spring:
  application:
    name: gateway-web-service
# 网关跨域问题配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':                    # 匹配所有请求
            allowedOrigins: "*"       # 跨域处理 允许所有的域
            allowedMethods:           # 支持的方法
                - GET
                - POST
                - PUT
                - DELETE
      routes:
        - id: mall_goods_route  # 唯一标识符
          uri: http://127.0.0.1:18001 # 路由的微服务地址uri
#           路由配置规则
          predicates:
#            - Host=cloud.mall.com**  # 域名规则配置
            - Path=/**  # 请求路径
           #请求数限流 名字不能随便写 ，使用默认的facatory
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"  # 用户的唯一标识
                redis-rate-limiter.replenishRate: 10  # 每秒有1个请求
                redis-rate-limiter.burstCapacity: 30   # 并发4个请求
        - id: mall_user_route
          uri: http://127.0.0.1:18086
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
  redis:
    host: 123.56.143.183
    port: 6379
    password: redis123
    database: 2

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true

