server:
  port: 8001

spring:
  application:
    name: gateway-web-service
# 网关跨域问题配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':                    # 匹配所有请求
            allowedOrigins: "*"       # 跨域处理 允许所有的域
            allowedMethods:           # 支持的方法
                - GET
                - POST
                - PUT
                - DELETE
      routes:
        - id: mall_goods_route  # 唯一标识符
          uri: http://127.0.0.1:18001 # 路由的微服务地址uri
#           路由配置规则
          predicates:
#            - Host=cloud.mall.com**  # 域名规则配置
            - Path=/album/**  # 请求路径
#        - name: RequestRateLimiter       #请求数限流 名字不能随便写 ，使用默认的facatory
#        - args:
#        - key-resolver: "#{@ipKeyResolver}"  # 用户的唯一标识
#        - redis-rate-limiter.replenishRate: 1  # 每秒有1个请求
#        - redis-rate-limiter.burstCapacity: 1   # 并发4个请求

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
