server:
  port: 18001
spring:
  application:
    name: goods-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.155.56.176:3306/shop_mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Wo123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
#feign:
#  hystrix:
#    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ytz.mall.goods.pojo