server:
  port: 9001
spring:
  application:
    name: oauth-service
  redis:
    host: 123.56.143.183
    port: 6379
    password: redis123
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    database: 3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.155.56.176:3306/shop_mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Wo123456
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: mall_shopping
  clientSecret: mall_shopping
  accessTokenUri: http://localhost:9001/oauth/token
  userAuthorizationUri: http://localhost:9001/oauth/authorize
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    secret: mall_shopping
    alias: mall_shopping
    password: mall_shopping
    location: classpath:/mallshopping.jks
