spring:
  servlet:
    multipart:
#      单个文件大小
      max-file-size: 10MB
#      总上传的数据大小
      max-request-size: 10MB
  application:
    name: file-service
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true